###############################################################################
# BBG Client Configuration
###############################################################################

#
# Parking System TCP server IPv4 address.
#
# Development:
#     127.0.0.1
#
# BeagleBone Green:
#     192.168.137.100
#
server_address = 192.168.137.100

#
# Parking System TCP server port.
#
server_port = 5000

#
# TCP process log file.
#
tcp_log_file = ../Logs/bbg_tcp.log

#
# I2C process log file.
#
i2c_log_file = ../Logs/bbg_i2c.log

#
# Enable console logging.
#
# Development:
#     1
#
# Daemon mode:
#     0
#
console_logging = 1
