#
# Parking System configuration file
#

#--------------------------------------------------
# Shared memory
#--------------------------------------------------

IPC_SHARED_MEMORY_KEY=0x1234

#--------------------------------------------------
# Database
#--------------------------------------------------

DATABASE_PATH=../Database/parking.db

#--------------------------------------------------
# Logging
#--------------------------------------------------

LOG_FILE=../Logs/database.log

TCP_SERVER_LOG_FILE=../Logs/tcp_server.log

ENABLE_CONSOLE_LOGGING=1


